name: Build site from Fork

on:
  workflow_call:
    inputs:
      version:
        description: the version of MarkBind to use. e.g. 3.1.1
        default: 'latest'
        type: string
      rootDirectory:
        description: read source files from the specified directory
        default: '.'
        type: string
      baseUrl:
        description: the base URL relative to your domain
        default: 'unsetFlag' # a flag indicating that baseUrl defaults to the one specified in site.json config file
        type: string
      siteConfig:
        description: the site config file to use
        default: 'site.json'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: curr-repo
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Checkout markbind-cli@master
        if: inputs.version == 'development'
        uses: actions/checkout@v3
        with:
          repository: MarkBind/markbind
          path: markbind-cli
      - name: Install markbind-cli@master
        if: inputs.version == 'development'
        run: |
          npm i -g npm@8.3.1
          cd markbind-cli
          npm run setup && npm run build:web
          cd packages/cli
          npm link
          cd ../../..
        shell: bash
      - name: Install a released version of markbind-cli
        if: inputs.version != 'development'
        run: |
          npm install -g markbind-cli@${{ inputs.version }}
        shell: bash
      - name: Build site
        run: |
          BASEURL="--baseUrl ${{ inputs.baseUrl }}" 
          if [[ "${{ inputs.baseUrl }}" == "unsetFlag" ]]; then
            BASEURL=""
            echo "Default baseUrl to the config file attribute"
          fi
          cd curr-repo
          markbind build ${{ inputs.rootDirectory }} ./_site \
          $BASEURL --site-config ${{ inputs.siteConfig }}
          cd ..
          echo "Site Built!"
        shell: bash
      - name: Save PR number and HEAD commit
        if: ${{ success() && github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NUMBER
          echo ${{ github.event.pull_request.head.sha }} > ./pr/SHA
      - name: Upload artifacts
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: site-artifacts
          retention-days: 1
          if-no-files-found: error
          path: |
            ./curr-repo/_site
            ./pr
