name: Build Fork PR

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Build site
        run: |
          npm install -g markbind-cli
          markbind build
      - name: Save PR number and HEAD commit
        if: ${{ success() && github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NUMBER
          echo ${{ github.event.pull_request.head.sha }} > ./pr/SHA
      - name: Upload artifacts 
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: site-artifacts
          path: |
            ./_site
            ./pr